### PR TITLE
Update dependencies and add new build target for modern browsers

### PR DESCRIPTION
**Pull request by Tofandel**
#263 

Updated all dev dependencies to use the new version of babel/webpack/eslint, since vuepress only supports webpack 4 a separate install of vuepress was made where the build takes place

The test were failing in exactly the same place, before and after update and it's actually because of https://github.com/iamstevendao/vue-tel-input/commit/75c2e76a51aba6ce31f024f7c57101cb9bb00ad0 nothing to do with the changes in this PR (which there are none to the code), so I also updated the failing test

This is the list of browsers that should work with the modern build, though the declared list of supported browsers is more restrictive
https://caniuse.com/async-functions (pretty much same as before except IE11 and Opera mini)

It shaves off 35% of the size of the minified build (and 50% of the non minified)

### CODE REVIEW

**Comment by iamstevendao** [comment]
@Tofandel Thanks you 🎉. I'm a bit confused tho, does this mean we need to publish both builds to npm?

**Comment by Tofandel** [comment]
Yes but it's both in one, basically all the builds are included in one publish, and you get to choose when importing which one you prefer (eg: if you need to support IE or not) the question is which one do we want to put by default? I left the previous one right now but I think eventually putting the modern-build as default in a breaking release down the line will make sense

I'd need to add some doc, but basically you can use import 

```
import VueTelInput from 'vue-tel-input/dist-modern/vue-tel-input.umd.js';
import 'vue-tel-input/dist-modern/vue-tel-input.css';
```

Or a webpack alias to get the new build

**Comment by Tofandel** [comment]
@iamstevendao I believe you need to update the circle ci file to use cypress/base:10 as well, as dependencies were installed on npm v7, and cypress/base:8 uses npm v6

**Comment by iamstevendao** [comment]
@Tofandel Thanks!!

**Pull request merged**
