### PR TITLE
add prop to be able disable country dropdown

### PR DESCRIPTION
**Pull request by dino4udo**
Add additional prop to be able to disable country dropdown

### CODE REVIEW

**Comment by Daniel4Digital** [comment]
Thanks for this! It was on my todo list to fix.

**Comment by dino4udo** [comment]
No problem. let me know if you have in mind smth else

**Comment by Daniel4Digital** [comment]
@iamstevendao Still missing this prop

**Comment by GoncaloNevesCorreia** [comment]
I miss this feature too

**Comment by iamstevendao** [comment]
@dino4udo Thanks for your help! Since there were a lot of conflicts introduced so I isolated your changes to: https://github.com/iamstevendao/vue-tel-input/commit/8fe46cc06fa35fcaacfc75c4eeace51520161092.
I will be released in the next patch

**Pull request closed without merging**
