### PR TITLE
feature: rewrite to Composition API

### PR DESCRIPTION
**Pull request by daniil4udo**
I know it's a lot of changes...  I didn't change any logic, just an attempt to add typings and Composition API

- Why Vue version upgraded? To be able to use `defineModel`
- Why `getDefault` moved to the `utils.ts` - there's an important limitation to keep in mind: defineProps() (and similar functions like defineEmits() or useSlots()) cannot reference locally declared variables within the same <script setup> block. This limitation arises because these API calls are hoisted outside of the setup function by the Vue compiler during the SFC compilation process. Hoisting means that these calls are moved to the top of the module scope, so they execute before any local variables are defined, thus they cannot reference those variables.

### CODE REVIEW

**Comment by iamstevendao** [comment]
@daniil4udo wow! that's huge & looks promising. thanks for your help!
Before we can merge, could you revert the formatting changes in `vue-tel-input.vue`? I assume it came automatically from your IDE and could be turned off? Just so it's easier for me to validate the actual changes. Thanks!

**Comment by daniil4udo** [comment]
Did for the template. Not sure I can do it inside the script tag

**Comment by iamstevendao** [comment]
@daniil4udo that's awesome! thanks a heap!

**Comment by iamstevendao** [comment]
@daniil4udo there are some errors when I try `npm run build`. could you help, please? thanks!

**Pull request merged**
